const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

const input_array = input.trim().split("\n").map(row => row.split(""));

module.exports = {input_array};